steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/primopoker:$COMMIT_SHA', '.']
  
  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/primopoker:$COMMIT_SHA']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'primopoker'
      - '--image=gcr.io/$PROJECT_ID/primopoker:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--max-instances=100'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--concurrency=1000'
      - '--timeout=3600'
      - '--set-env-vars=ENVIRONMENT=production'

# Store the image in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/primopoker:$COMMIT_SHA'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
